title: Arian Xhezairi
description: Xhezairbey Cronicles
baseurl: ""
# domain: xhezairi.com
# url: https://xhezairi.com
url: https://xhezairbey.github.io

# site settings
taglong: erudite • engineer • ex-military
tagshort: ✪ The Supreme Leader

# author settings
author:
  username: xhezairbey
  name: Arian Xhezairi
  email: name@thisdomain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  x: xhezairbey
  youtube: xhezairbey
  github: xhezairbey
  linkedin: xhezairbey
  website: https://mamiresedje.com

collections:
  posts:
    output: true
    permalink: /:collection/:title

theme: cvless
# plugins:
  # - jekyll-feed

# feed:
#   path: atom.xml

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
