title: Arian Xhezairi
description: Xhezairbey Cronicles
baseurl: ""
# domain: xhezairi.com
# url: https://xhezairi.com
url: https://xhezairbey.github.io

theme: cvless

# site settings
taglong: author
tagshort: Supreme Leader

# author settings
author:
  name: Arian Xhezairi
  email: name@thisdomain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  github: xhezairbey
  linkedin: xhezairbey
  x: xhezairbey
  facebook: xhezairbeg
  instagram: xhezairbeg

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
